### ISSUE TITLE
deprecated version of the Android embedding

### ISSUE THREAD

**Issue by kamyar75** [jaumard/sms_autofill#134] opened 2021-09-13 15:24 UTC
please solve this problem:

The plugin `sms_autofill` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

thanks.

**Comment by jaumard** [comment] 2021-09-13 15:25
duplicate of https://github.com/jaumard/sms_autofill/issues/133

**Closed by jaumard** 2021-09-13 15:25 UTC
