### ISSUE TITLE
i have more than simCard inserted on device but sms_autofill get first number only ??

### ISSUE THREAD

**Issue by husseinalkoosh** [jaumard/sms_autofill#32] opened 2020-02-25 15:44 UTC

**Comment by amin-aljebbeh** [comment] 2020-02-27 16:47
Try to use PinFieldAutoFill instead of TextFieldPinAutoFill

**Comment by jaumard** [comment] 2021-03-15 13:17
closing as duplicate of #29

**Closed by jaumard** 2021-03-15 13:17 UTC
